### PR TITLE
Support Localization

### PR DESCRIPTION
**Pull request by SCullman**

### CODE REVIEW

**Comment by Zaid-Ajaj** [comment]
Thanks a lot! Will be published soon :smile:

**Comment by Zaid-Ajaj** [comment]
@SCullman Published v1.4.0 with the locales predefined. You example becomes: 
```fs
Flatpickr.flatpickr [Flatpickr.Locale Flatpickr.Locales.german]
```
where the `Flatpickr.Locales` module contains 30+ locales

**Comment by SCullman** [comment]
Perfect. I thought also about including all locales, but decided against to reduce the size of the lib.
Thank you for your quick merge!

**Comment by Zaid-Ajaj** [comment]
I think Webpack should be able to remove unused import, not sure if there is extra configuration needed to do so but nonetheless, these locale files are very small containing object literals for local data so I don't think it is a big difference

**Pull request merged**
