### PR TITLE
code is pushed to latest version

### PR DESCRIPTION
**Pull request by kunjee17**
@Zaid-Ajaj I have corrected the code to support latest Fable.Core, Elmish and React. But I was facing issue while running build. It would be great if you can check it out. And also push Fake to latest version.

Let me know if anything is required from my end.

### CODE REVIEW

**Comment by Zaid-Ajaj** [comment]
Hello @kunjee17, thanks a lot for updates, I didn't know fable-compiler already went stable. Though it seems that `Fable.Core` is still in beta. I would like to push every library to stable release when `Fable.Core` is stable too.

As for running the builds, I think you still need `mono` and then it is just a matter of `./build.sh`  or `build.cmd` if you are on Windows

> Travis CI seems to be broken too, I will fix it

**Comment by kunjee17** [comment]
@Zaid-Ajaj Build.sh was not working as I have updated fable-compiler as well. Basically there are breaking changes with latest fable. So, I guess there are little bit more changes required from the build.fsx and webpack.config perspective. 

So, It would be great if you can have a look at it and update them. 

> And, yes it could wait till full release if you are not releasing beta like other libraries.

**Comment by Zaid-Ajaj** [comment]
> Build.sh was not working as I have updated fable-compiler as well. Basically there are breaking changes with latest fable. So, I guess there are little bit more changes required from the build.fsx and webpack.config perspective.

Yeah things have to be just right everywhere to make the build work. I think build.fsx is using `dotnet-fable` to run the Fable compilation instead of invoking webpack. 

> And, yes it could wait till full release if you are not releasing beta like other libraries.

Nah I will release it in beta today :)

**Comment by Zaid-Ajaj** [comment]
Hello @kunjee17, I just managed to publish a beta release as of version 3.0.0-beta and should be available soon when Nuget does it's magic. 

The problem in the build was because of outdated webpack and webpack-cli versions. Let's see if travis is happy...

**Pull request merged**
